### ISSUE TITLE
Jest fails after bumping to v0.0.8 with jsdom error

### ISSUE THREAD

**Issue by shobhitsharma** [stroeer/stroeer-videoplayer-default-ui#11]
Somewhere in minified version `stroeer-videoplayer-default-ui/dist/StroeerVideoplayer-default-ui.cjs.js:376:21` jsdom is throwing exception during test with jest. This has happened after I tried to update to `v.0.0.8`. 

```bash
console.error
Error: Not implemented: HTMLMediaElement.prototype.load
    at module.exports (/Users/shobhitsharma/Workspace/Stroeer/paper/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
    at HTMLVideoElementImpl.load (/Users/shobhitsharma/Workspace/Stroeer/paper/node_modules/jsdom/lib/jsdom/living/nodes/HTMLMediaElement-impl.js:112:5)
    at HTMLVideoElement.load (/Users/shobhitsharma/Workspace/Stroeer/paper/node_modules/jsdom/lib/jsdom/living/generated/HTMLMediaElement.js:111:34)
    at UI.init (/Users/shobhitsharma/Workspace/Stroeer/paper/node_modules/@stroeer/stroeer-videoplayer-default-ui/dist/StroeerVideoplayer-default-ui.cjs.js:376:21)
    at StrooerVideoplayer.initUI (/Users/shobhitsharma/Workspace/Stroeer/paper/node_modules/@stroeer/stroeer-videoplayer/dist/StroeerVideoplayer.cjs.js:116:20)
    at new StrooerVideoplayer (/Users/shobhitsharma/Workspace/Stroeer/paper/node_modules/@stroeer/stroeer-videoplayer/dist/StroeerVideoplayer.cjs.js:241:14)
    at /Users/shobhitsharma/Workspace/Stroeer/paper/packages/ui-library/src/components/VideoElement/VideoElement.tsx:51:32
    at invokePassiveEffectCreate (/Users/shobhitsharma/Workspace/Stroeer/paper/node_modules/react-dom/cjs/react-dom.development.js:23487:20)
    at HTMLUnknownElement.callCallback (/Users/shobhitsharma/Workspace/Stroeer/paper/node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at HTMLUnknownElement.callTheUserObjectsOperation (/Users/shobhitsharma/Workspace/Stroeer/paper/node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30) undefined

at VirtualConsole.<anonymous> (../../node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
at module.exports (../../node_modules/jsdom/lib/jsdom/browser/not-implemented.js:12:26)
at HTMLVideoElementImpl.load (../../node_modules/jsdom/lib/jsdom/living/nodes/HTMLMediaElement-impl.js:112:5)
at HTMLVideoElement.load (../../node_modules/jsdom/lib/jsdom/living/generated/HTMLMediaElement.js:111:34)
at UI.init (../../node_modules/@stroeer/stroeer-videoplayer-default-ui/dist/StroeerVideoplayer-default-ui.cjs.js:376:21)
at StrooerVideoplayer.initUI (../../node_modules/@stroeer/stroeer-videoplayer/dist/StroeerVideoplayer.cjs.js:116:20)
at new StrooerVideoplayer (../../node_modules/@stroeer/stroeer-videoplayer/dist/StroeerVideoplayer.cjs.js:241:14)
```

I'm not sure exact details, feel free to ask me if I can reproduce it for you in more details.

**Comment by walialu** [comment]
@ennoStroeer can you look into this, please?

**Comment by ennoStroeer** [comment]
accepted

**Comment by ennoStroeer** [comment]
can reproduce it

**Comment by walialu** [comment]
Should be fixed with #12. Can you confirm that @shobhitsharma?

**Comment by shobhitsharma** [comment]
@walialu @ennoStroeer I've tried to bump in our [last chore](https://github.com/stroeer/paper/pull/818), it seems to have worked. This issue can be closed!

**Comment by ennoStroeer** [comment]
I am closing it!
